version: '3.8'
services:
  db:
    image: postgres:13.12
    container_name: challenge_postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: lgedv2024
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      retries: 5

  web:
    build: .
    container_name: challenge_web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db # Không phải localhost!
      DB_USER: root
      DB_PASSWORD: lgedv2024
      DB_NAME: user_db
    ports:
      - "5000:5000"
